/* ════════════════════════════════════════════════════════
   AIGENEV7 — Static Agent & Model Data
   No API required. Edit these to customize your site.
   ════════════════════════════════════════════════════════ */

window.AIGENEV7_AGENTS = [
  {
    id: 'default',
    name: 'Coding Assistant',
    emoji: '🤖',
    description: 'General-purpose coding assistant',
    systemPrompt: 'You are an expert programming assistant. Help the user write clean, efficient, well-documented code. Provide complete solutions with explanations.',
  },
  {
    id: 'code-reviewer',
    name: 'Code Reviewer',
    emoji: '🔍',
    description: 'Reviews code for bugs, security, and best practices',
    systemPrompt: 'You are a senior code reviewer. Analyze code for bugs, security vulnerabilities, performance issues, and style violations. Always provide specific, actionable feedback. Format your review with: Issues Found, Suggestions, and a Summary.',
  },
  {
    id: 'debugger',
    name: 'Debugger',
    emoji: '🐛',
    description: 'Focused on finding and fixing bugs',
    systemPrompt: 'You are a debugging expert. When given error messages or buggy code, systematically identify the root cause, explain why it happens, and provide the fix. Use a hypothesis-driven approach.',
  },
  {
    id: 'tech-writer',
    name: 'Technical Writer',
    emoji: '📝',
    description: 'Generates documentation, READMEs, API docs',
    systemPrompt: 'You are a technical writer. Write clear, concise, well-structured documentation. Use proper Markdown formatting. Include code examples, usage guides, and API references where appropriate.',
  },
  {
    id: 'sql-expert',
    name: 'SQL Expert',
    emoji: '🗄️',
    description: 'Database queries and schema design',
    systemPrompt: 'You are a SQL and database expert. Write optimized queries, design normalized schemas, and suggest indexing strategies. Always consider performance and explain your reasoning.',
  },
  {
    id: 'architect',
    name: 'System Architect',
    emoji: '🏗️',
    description: 'Architecture and design patterns',
    systemPrompt: 'You are a software architect. Design scalable, maintainable system architectures. Discuss trade-offs between different approaches. Use diagrams (ASCII art) and outline component interactions.',
  },
  {
    id: 'security-auditor',
    name: 'Security Auditor',
    emoji: '🔒',
    description: 'Security vulnerability analysis',
    systemPrompt: 'You are a security auditor. Analyze code for OWASP Top 10 vulnerabilities, injection flaws, authentication issues, and data exposure risks. Provide CVSS-style severity ratings and remediation steps.',
  },
  {
    id: 'test-engineer',
    name: 'Test Engineer',
    emoji: '🧪',
    description: 'Writes unit tests and test plans',
    systemPrompt: 'You are a QA engineer. Write comprehensive unit tests, integration tests, and test plans. Cover edge cases, error paths, and happy paths. Use the testing framework appropriate for the language.',
  },
  {
    id: 'pythonista',
    name: 'Python Expert',
    emoji: '🐍',
    description: 'Python-specific coding assistant',
    systemPrompt: 'You are a Python expert. Write Pythonic code following PEP 8. Use type hints, list comprehensions, generators, and appropriate design patterns. Suggest modern Python features where beneficial.',
  },
  {
    id: 'react-dev',
    name: 'React Developer',
    emoji: '⚛️',
    description: 'React/Next.js frontend expert',
    systemPrompt: 'You are a React expert. Build components using modern React patterns (hooks, functional components). Use TypeScript, consider performance, accessibility, and state management. Provide complete component code with styles.',
  },
  {
    id: 'mentor',
    name: 'Mentor Mode',
    emoji: '🎓',
    description: 'Guided learning with explanations',
    systemPrompt: 'You are a patient coding mentor. Guide the user through problems step by step. Don\'t give complete solutions immediately ask questions, provide hints, and help them arrive at the answer themselves. Explain concepts thoroughly.',
  },
  {
    id: 'socratic',
    name: 'Socratic Debugger',
    emoji: '💭',
    description: 'Ask questions to help user debug their own code',
    systemPrompt: 'Use the Socratic method: Ask probing questions to help the user discover bugs and solutions themselves. Don\'t give direct answers guide them through reasoning. Ask one question at a time.',
  },
  {
    id: 'quantum-dev',
    name: 'Quantum Developer',
    emoji: '⚛️',
    description: 'Expert in quantum computing, algorithms, and Qiskit/Cirq/Q#',
    systemPrompt: 'You are a quantum computing expert. Explain quantum algorithms, write quantum code (Qiskit, Cirq, Q#), and help with quantum circuit design. The built-in quantum simulator at js/quantum.js supports H, X, Y, Z, S, T, CNOT, SWAP, Toffoli gates.',
  },
]

window.AIGENEV7_MODELS = [
  { id: 'claude-sonnet-4', displayName: 'Claude Sonnet 4', provider: 'Anthropic', description: 'Balanced performance with reasoning', multimodal: true },
  { id: 'claude-haiku-4', displayName: 'Claude Haiku 4', provider: 'Anthropic', description: 'Fast & affordable', multimodal: true },
  { id: 'deepseek-v4-pro', displayName: 'DeepSeek V4 Pro', provider: 'DeepSeek', description: 'Smartest reasoning model' },
  { id: 'deepseek-v4', displayName: 'DeepSeek V4', provider: 'DeepSeek', description: 'Fast everyday model' },
  { id: 'gpt-5', displayName: 'GPT-5', provider: 'OpenAI', description: 'Latest flagship model' },
  { id: 'gpt-5-mini', displayName: 'GPT-5 Mini', provider: 'OpenAI', description: 'Fast & cost-effective' },
  { id: 'gemini-2.5-pro', displayName: 'Gemini 2.5 Pro', provider: 'Google', description: 'Premium reasoning' },
  { id: 'gemini-2.5-flash', displayName: 'Gemini 2.5 Flash', provider: 'Google', description: 'Fast & efficient' },
  { id: 'grok-4', displayName: 'Grok 4', provider: 'xAI', description: 'Uncensored by design' },
  { id: 'kimi-k2.6', displayName: 'Kimi K2.6', provider: 'Moonshot', description: 'Balanced performance' },
  { id: 'mimo-2.5-pro', displayName: 'MiMo 2.5 Pro', provider: 'MiMo', description: 'Deep thinking' },
  { id: 'minimax-m3', displayName: 'MiniMax M3', provider: 'MiniMax', description: 'Smartest & Fastest' },
  { id: 'nvidia-llama-3.1-70b', displayName: 'Llama 3.1 70B', provider: 'NVIDIA', description: 'Open source powerhouse' },
  { id: 'nvidia-nemotron-4', displayName: 'Nemotron 4', provider: 'NVIDIA', description: 'Enterprise-grade reasoning' },
]

window.AIGENEV7_FEATURES = [
  { icon: '🔥', title: 'Unlimited Usage', desc: 'No token limits, no rate limits, no session caps. Code as long as you want.' },
  { icon: '🚫', title: 'Uncensored', desc: 'No content filters, no safety classifiers, no output restrictions.' },
  { icon: '🌐', title: 'All Models', desc: 'Claude, GPT, DeepSeek, Gemini, Grok, Kimi, MiMo, MiniMax any model.' },
  { icon: '⚡', title: 'Zero Config', desc: 'No subscriptions, no credit cards, no account required.' },
  { icon: '🛠️', title: 'Full Agent', desc: 'Edits files, runs commands, searches code, browses the web.' },
  { icon: '🔓', title: 'Open Source', desc: 'MIT licensed. Fork it, modify it, self-host it.' },
]

window.AIGENEV7_SUBTITLES = [
  'Free AI coding assistant. No subscription. No censorship.',
  '10 providers. 28 models. One local agent.',
  'DeepSeek. OpenAI. Anthropic. Gemini. Grok. More.',
  'Your code stays on your machine. Always.',
  'Built by CONSTANZA. For everyone.'
]

// ── Subscription Plans ──────────────────────────────────────────────────
// Pricing tiers with different billing periods.
// Each period has: price, label, savings message.
// The badge property highlights the recommended plan.

window.AIGENEV7_PLANS = [
  {
    id: 'weekly',
    name: 'Weekly Pass',
    emoji: '🚀',
    description: 'Perfect for trying out unlimited AI coding.',
    badge: null,
    prices: {
      weekly: { price: 10, period: 'week', label: '/week', savings: null },
    },
    features: [
      'All 14 supported models',
      'Unlimited token usage',
      'Standard response priority',
      'Email support',
      'Access to all agent personas',
      'Quantum Lab access',
    ],
    cta: 'Subscribe Weekly',
    popular: false,
  },
  {
    id: 'monthly',
    name: 'Monthly Pro',
    emoji: '⭐',
    description: 'For regular developers who code every day.',
    badge: 'Most Popular',
    prices: {
      weekly: { price: 15, period: 'week', label: '/week', savings: 'Save 40% vs Weekly' },
      monthly: { price: 25, period: 'month', label: '/month', savings: null },
      yearly: { price: 20, period: 'month', label: '/month', savings: 'Save 20% vs Monthly' },
    },
    features: [
      'All 14 supported models',
      'Unlimited token usage',
      'Priority response queue',
      'Priority email support',
      'All agent personas + gallery',
      'Quantum Lab + CLI access',
      'Early access to new models',
    ],
    cta: 'Subscribe Monthly',
    popular: true,
  },
  {
    id: 'quarterly',
    name: 'Quarterly Premium',
    emoji: '💎',
    description: 'Serious developers wanting the best value.',
    badge: 'Best Value',
    prices: {
      weekly: { price: 12, period: 'week', label: '/week', savings: 'Save 52% vs Weekly' },
      monthly: { price: 20, period: 'month', label: '/month', savings: 'Save 20% vs Monthly' },
      quarterly: { price: 60, period: 'quarter', label: '/quarter', savings: null },
    },
    features: [
      'All 14+ supported models',
      'Unlimited token usage',
      'High priority response queue',
      'Priority email + chat support',
      'All agents + gallery + custom',
      'Quantum Lab + CLI + API',
      'Early access to features',
      'Beta model access',
    ],
    cta: 'Subscribe Quarterly',
    popular: false,
  },
  {
    id: 'yearly',
    name: 'Yearly Elite',
    emoji: '👑',
    description: 'Power users who want it all, with maximum savings.',
    badge: 'Best Savings',
    prices: {
      weekly: { price: 10, period: 'week', label: '/week', savings: 'Save 60% vs Weekly' },
      monthly: { price: 15, period: 'month', label: '/month', savings: 'Save 40% vs Monthly' },
      yearly: { price: 180, period: 'year', label: '/year', savings: null },
    },
    features: [
      'All models + priority access',
      'Unlimited token usage',
      'Top priority response queue',
      'VIP support (email + chat + 1:1)',
      'Everything: agents, gallery, quantum',
      'Full API access + CLI',
      'Early access to all features',
      'Beta models + experimental',
      'Name in release notes',
      'Direct line to maintainer',
    ],
    cta: 'Subscribe Yearly',
    popular: false,
  },
  {
    id: 'lifetime',
    name: 'Lifetime Legend',
    emoji: '🏆',
    description: 'One payment. Forever access. For the true believers.',
    badge: 'Limited Edition',
    prices: {
      lifetime: { price: 499, period: 'once', label: ' once', savings: null },
    },
    features: [
      'Everything in Yearly Elite — forever',
      'No recurring payments ever',
      'VIP support for life',
      'Name in AIGENEV7 credits',
      'Project governance vote',
      'Private maintainer chat',
      'Custom feature requests',
      'Lifetime early access',
      'Exclusive Legend badge on profile',
      'Founding member status',
    ],
    cta: 'Get Lifetime Access',
    popular: false,
  },
]

// ── aigen7ev.store — Products ────────────────────────────────────────────
// Complete product catalog: AI plans, agent packs, digital, merch, consulting

window.AIGENEV7_STORE_PRODUCTS = [
  // ── AI Subscription Plans ──
  {
    id: 'sub-weekly',
    category: 'subscriptions',
    name: 'Weekly AI Pass',
    emoji: '🚀',
    description: 'Unlimited AI coding for one week. All 14+ models, all agent personas, uncensored.',
    price: 10.00,
    unit: 'week',
    image: null,
    featured: true,
    stripePriceId: null, // Set after Stripe dashboard setup
  },
  {
    id: 'sub-monthly',
    category: 'subscriptions',
    name: 'Monthly Pro',
    emoji: '⭐',
    description: 'Unlimited AI coding for one month. Priority queue, early access to new models.',
    price: 25.00,
    unit: 'month',
    image: null,
    featured: true,
    popular: true,
    stripePriceId: null,
  },
  {
    id: 'sub-yearly',
    category: 'subscriptions',
    name: 'Yearly Elite',
    emoji: '👑',
    description: 'Unlimited AI for one year. VIP support, early access, full API. Best value.',
    price: 180.00,
    unit: 'year',
    image: null,
    featured: true,
    savings: '$25/mo — Save 40%',
    stripePriceId: null,
  },
  {
    id: 'sub-lifetime',
    category: 'subscriptions',
    name: 'Lifetime Legend',
    emoji: '🏆',
    description: 'One payment. Forever access. VIP support, project governance, founding member status.',
    price: 499.00,
    unit: 'once',
    image: null,
    featured: true,
    stripePriceId: null,
  },

  // ── Agent Persona Packs ──
  {
    id: 'pack-starter',
    category: 'packs',
    name: 'Starter Agent Pack',
    emoji: '🎒',
    description: '5 ready-to-use agent personas: Debugger, Tech Writer, SQL Expert, Mentor, Security Auditor.',
    price: 9.99,
    unit: 'once',
    image: null,
    featured: false,
  },
  {
    id: 'pack-pro',
    category: 'packs',
    name: 'Pro Agent Pack',
    emoji: '💼',
    description: '15 advanced agent personas including Architect, Game Dev, Blockchain, CLI Wizard, and more.',
    price: 24.99,
    unit: 'once',
    image: null,
    featured: true,
    popular: true,
  },
  {
    id: 'pack-mega',
    category: 'packs',
    name: 'Mega Agent Bundle',
    emoji: '📦',
    description: '50+ agent personas covering every niche: quantum, embedded, bioinformatics, legal, and more.',
    price: 49.99,
    unit: 'once',
    image: null,
    featured: true,
    savings: 'Save $30 vs individual',
  },
  {
    id: 'pack-custom',
    category: 'packs',
    name: 'Custom Agent Builder',
    emoji: '🔧',
    description: 'Design your own agent personas. Includes a web form + CLI generator. (5 custom slots)',
    price: 14.99,
    unit: 'once',
    image: null,
    featured: false,
  },

  // ── Digital Downloads ──
  {
    id: 'dl-quantum-source',
    category: 'digital',
    name: 'Quantum Lab Source Code',
    emoji: '⚛️',
    description: 'Full source code for the browser-based quantum circuit simulator. MIT licensed. Import into any project.',
    price: 19.99,
    unit: 'once',
    image: null,
    featured: true,
  },
  {
    id: 'dl-agent-kit',
    category: 'digital',
    name: 'Custom Agent Template Kit',
    emoji: '🧩',
    description: 'Templates and examples for creating custom agent personas. Includes 10 sample prompts and patterns.',
    price: 9.99,
    unit: 'once',
    image: null,
    featured: false,
  },
  {
    id: 'dl-theme-pack',
    category: 'digital',
    name: 'CLI Theme Pack',
    emoji: '🎨',
    description: '5 premium CLI color themes, custom prompt styles, and terminal configurations.',
    price: 4.99,
    unit: 'once',
    image: null,
    featured: false,
  },
  {
    id: 'dl-ebook',
    category: 'digital',
    name: 'E-Book: Building AI Agents',
    emoji: '📖',
    description: 'Complete guide to building, deploying, and monetizing AI coding agents. 200+ pages with code examples.',
    price: 29.99,
    unit: 'once',
    image: null,
    featured: true,
  },

  // ── Merchandise ──
  {
    id: 'merch-tshirt',
    category: 'merch',
    name: 'AIGENEV7 T-Shirt',
    emoji: '👕',
    description: 'Premium cotton t-shirt with AIGENEV7 logo. Available in S/M/L/XL/XXL. Black.',
    price: 24.99,
    unit: 'once',
    image: null,
    featured: true,
  },
  {
    id: 'merch-hoodie',
    category: 'merch',
    name: 'AIGENEV7 Hoodie',
    emoji: '🧥',
    description: 'Heavyweight fleece hoodie with embroidered AIGENEV7 logo. S/M/L/XL. Black.',
    price: 49.99,
    unit: 'once',
    image: null,
    featured: true,
  },
  {
    id: 'merch-stickers',
    category: 'merch',
    name: 'AIGENEV7 Sticker Pack',
    emoji: '🦊',
    description: '6 vinyl stickers with AIGENEV7 logo, quantum circuits, and ASCII art. Waterproof.',
    price: 4.99,
    unit: 'once',
    image: null,
    featured: false,
  },
  {
    id: 'merch-mug',
    category: 'merch',
    name: 'AIGENEV7 Ceramic Mug',
    emoji: '☕',
    description: '11oz ceramic mug with heat-reactive AIGENEV7 logo. Changes color with hot drinks.',
    price: 14.99,
    unit: 'once',
    image: null,
    featured: false,
  },

  // ── Consulting / Services ──
  {
    id: 'svc-code-review',
    category: 'services',
    name: '1-Hour Code Review',
    emoji: '🔍',
    description: 'One-on-one code review session with a senior developer. Get actionable feedback on your codebase.',
    price: 99.00,
    unit: 'once',
    image: null,
    featured: false,
  },
  {
    id: 'svc-architecture',
    category: 'services',
    name: '4-Hour Architecture Workshop',
    emoji: '🏗️',
    description: 'Half-day workshop covering system design, architecture patterns, and best practices for your project.',
    price: 349.00,
    unit: 'once',
    image: null,
    featured: true,
  },
  {
    id: 'svc-full-day',
    category: 'services',
    name: 'Full Day Sprint (8h)',
    emoji: '⚡',
    description: 'Intensive 8-hour development sprint with an expert. Build features, fix bugs, optimize performance.',
    price: 649.00,
    unit: 'once',
    image: null,
    featured: true,
  },
  {
    id: 'svc-retainer',
    category: 'services',
    name: 'Monthly Retainer (20h)',
    emoji: '🤝',
    description: '20 hours of dedicated development time per month. Priority access, weekly check-ins, Slack support.',
    price: 1999.00,
    unit: 'monthly',
    image: null,
    featured: false,
  },
]

// Category display config
window.AIGENEV7_STORE_CATEGORIES = {
  subscriptions: { label: 'AI Subscriptions', emoji: '✨', desc: 'Unlimited AI access plans' },
  packs: { label: 'Agent Packs', emoji: '🧠', desc: 'Pre-built agent personas' },
  digital: { label: 'Digital Downloads', emoji: '💾', desc: 'Source code, templates, e-books' },
  merch: { label: 'Merchandise', emoji: '👕', desc: 'Wear the brand' },
  services: { label: 'Consulting', emoji: '🤝', desc: 'Expert developer services' },
}

// ── Shared Agent Gallery ────────────────────────────────────────────────
// Community-contributed agent personas. Users can browse and download.
// To add your own, submit a PR or use the /agent-export CLI command.

window.AIGENEV7_GALLERY = [
  {
    id: 'data-scientist',
    name: 'Data Scientist',
    emoji: '📊',
    description: 'Expert in data analysis, ML, and statistical modeling',
    tags: ['popular', 'data', 'ml'],
    author: '@constanza8999',
    systemPrompt: 'You are a senior data scientist. Analyze data, build ML models, and communicate insights. Write clean Python code using pandas, numpy, scikit-learn, and matplotlib. Explain statistical concepts clearly and suggest appropriate models for the data.',
  },
  {
    id: 'devops-engineer',
    name: 'DevOps Engineer',
    emoji: '🔧',
    description: 'Infrastructure, CI/CD, and deployment expert',
    tags: ['popular', 'infra', 'docker'],
    author: '@constanza8999',
    systemPrompt: 'You are a DevOps engineer. Design CI/CD pipelines, manage cloud infrastructure, and automate deployments. Provide Dockerfiles, docker-compose configs, Kubernetes manifests, and Terraform scripts. Consider security, scalability, and cost optimization.',
  },
  {
    id: 'fullstack-dev',
    name: 'Full Stack Developer',
    emoji: '🌐',
    description: 'Frontend + backend + database — the whole stack',
    tags: ['popular', 'web', 'fullstack'],
    author: '@constanza8999',
    systemPrompt: 'You are a full stack developer. Build complete web applications end-to-end. Handle frontend (React/Vue), backend (Node/Python/Go), database (SQL/NoSQL), and deployment. Write clean, well-architected code with proper error handling and testing.',
  },
  {
    id: 'rustacean',
    name: 'Rust Expert',
    emoji: '🦀',
    description: 'Systems programming with Rust — safe, fast, concurrent',
    tags: ['new', 'systems', 'rust'],
    author: '@constanza8999',
    systemPrompt: 'You are a Rust expert. Write idiomatic, safe, and performant Rust code. Use proper error handling with Result/Option, leverage the type system, and apply ownership/borrowing rules correctly. Suggest cargo tools, crates, and best practices for systems programming.',
  },
  {
    id: 'game-dev',
    name: 'Game Developer',
    emoji: '🎮',
    description: 'Game design, graphics, and game engine development',
    tags: ['new', 'games', 'graphics'],
    author: '@constanza8999',
    systemPrompt: 'You are a game developer. Design game mechanics, implement rendering pipelines, and optimize performance. Use Godot, Unity, or Unreal Engine. Write shaders, handle physics, and manage game state. Consider frame timing, memory management, and player experience.',
  },
  {
    id: 'mobile-dev',
    name: 'Mobile Developer',
    emoji: '📱',
    description: 'iOS and Android app development expert',
    tags: ['specialized', 'mobile', 'swift'],
    author: '@constanza8999',
    systemPrompt: 'You are a mobile developer. Build native iOS (Swift/SwiftUI) and Android (Kotlin/Jetpack Compose) apps. Handle platform-specific APIs, app lifecycle, navigation, and state management. Consider performance, battery life, and platform design guidelines.',
  },
  {
    id: 'blockchain-dev',
    name: 'Blockchain Developer',
    emoji: '⛓️',
    description: 'Smart contracts, dApps, and Web3 development',
    tags: ['specialized', 'web3', 'solidity'],
    author: '@constanza8999',
    systemPrompt: 'You are a blockchain developer. Write secure smart contracts (Solidity, Rust for Solana), build dApps with web3 libraries, and understand consensus mechanisms. Always prioritize security — reentrancy, overflow, and access control. Explain gas optimization and testing strategies.',
  },
  {
    id: 'ai-researcher',
    name: 'AI Researcher',
    emoji: '🧠',
    description: 'ML/AI research, transformers, and deep learning',
    tags: ['specialized', 'ai', 'research'],
    author: '@constanza8999',
    systemPrompt: 'You are an AI/ML researcher. Understand transformers, attention mechanisms, diffusion models, reinforcement learning, and neural network architectures. Write PyTorch/TensorFlow code. Discuss trade-offs between model architectures, training strategies, and evaluation metrics.',
  },
  {
    id: 'cli-wizard',
    name: 'CLI Wizard',
    emoji: '⌨️',
    description: 'Command-line tools, shell scripting, and terminal mastery',
    tags: ['fun', 'cli', 'bash'],
    author: '@constanza8999',
    systemPrompt: 'You are a CLI expert. Build command-line tools, write shell scripts, and master terminal workflows. Use Node.js (commander/yargs), Python (click/argparse), or Go (cobra). Suggest useful one-liners, shell aliases, and terminal productivity hacks.',
  },
  {
    id: 'accessibility-advocate',
    name: 'Accessibility Advocate',
    emoji: '♿',
    description: 'WCAG, ARIA, and inclusive design specialist',
    tags: ['fun', 'a11y', 'inclusive'],
    author: '@constanza8999',
    systemPrompt: 'You are an accessibility expert. Ensure web content meets WCAG 2.2 AA/AAA standards. Write semantic HTML, use ARIA attributes correctly, and test with screen readers. Discuss color contrast, keyboard navigation, focus management, and assistive technology considerations.',
  },
]
